import { Map, Marker } from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import { miniatureSrc, previewSrc } from './mediaAssets'
import { formatShortTime } from './dates'
import { isSmallDevice } from './deviceBudget'

/**
 * The one map engine, MapLibre GL, with the shared pins, piles, clock chip and
 * basemap providers. Every map on the site is built from here, so they cannot
 * drift. MapLibre is imported only by this module, reached from the lazy map
 * views and the async picker. See docs/features/maps.md.
 */
export { Marker }

const MAPTOOLKIT_LOGO = 'https://www.maptoolkit.org/assets/logo-primary.svg'
const MAPTOOLKIT_ATTRIBUTION =
  '&copy; <a href="https://www.maptoolkit.com/copyright/">Maptoolkit</a> ' +
  '&copy; <a href="https://www.openstreetmap.org/copyright">Openstreetmap</a>'
const OPENFREEMAP_ATTRIBUTION =
  '&copy; <a href="https://openfreemap.org/">OpenFreeMap</a> ' +
  '&copy; <a href="https://www.openmaptiles.org/">OpenMapTiles</a> ' +
  'Data from <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
const CARTO_ATTRIBUTION =
  '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> ' +
  '&copy; <a href="https://carto.com/attributions">CARTO</a>'

/*
  Basemap providers. A `vector` provider is a MapLibre style URL; a `raster` one
  is a tile URL wrapped in a style of our own, so MapLibre treats both the same
  and a scheme change is one `setStyle`. See docs/features/maps.md.
*/
const PROVIDERS = {
  carto: {
    kind: 'raster',
    attribution: CARTO_ATTRIBUTION,
    hosts: ['basemaps.cartocdn.com'],
    styles: {
      light: 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
      dark: 'https://{s}.basemaps.cartocdn.com/rastertiles/dark_all/{z}/{x}/{y}{r}.png',
    },
  },
  maptoolkit: {
    kind: 'vector',
    attribution: MAPTOOLKIT_ATTRIBUTION,
    logo: MAPTOOLKIT_LOGO,
    hosts: ['tiles.maptoolkit.org', 'fonts.maptoolkit.org', 'icons.maptoolkit.org'],
    styles: {
      light: '/map/maptoolkit-light.json',
      dark: '/map/maptoolkit-dark.json',
    },
  },
  openfreemap: {
    kind: 'vector',
    attribution: OPENFREEMAP_ATTRIBUTION,
    hosts: ['tiles.openfreemap.org'],
    styles: {
      light: 'https://tiles.openfreemap.org/styles/bright',
      // Bright's own cartography in night tones, generated by the build script.
      dark: '/map/openfreemap-dark.json',
    },
  },
}

/** The provider on show: `maptoolkit` unless the environment names another. */
export const MAP_PROVIDER = PROVIDERS[import.meta.env.VITE_MAP_PROVIDER]
  ? import.meta.env.VITE_MAP_PROVIDER
  : 'maptoolkit'

/**
 * What a scheme needs: the style to hand MapLibre, the attribution its licence
 * requires, and the logo if the provider wants one. `VITE_MAP_STYLE_LIGHT` /
 * `_DARK` override the URL, so a custom or self-hosted style is an env change.
 */
export function mapStyleFor(scheme) {
  const provider = PROVIDERS[MAP_PROVIDER]
  const key = scheme === 'dark' ? 'dark' : 'light'
  const override =
    key === 'dark' ? import.meta.env.VITE_MAP_STYLE_DARK : import.meta.env.VITE_MAP_STYLE_LIGHT
  const url = override || provider.styles[key]
  const attribution = import.meta.env.VITE_MAP_ATTRIBUTION || provider.attribution
  const logo = provider.logo ?? null

  if (provider.kind === 'vector') return { style: url, attribution, logo }

  return {
    style: {
      version: 8,
      sources: { base: { type: 'raster', tiles: [url], tileSize: 256 } },
      layers: [{ id: 'base', type: 'raster', source: 'base' }],
    },
    attribution,
    logo,
  }
}

/** Japan, roughly, for when there is nothing to fit the view to. `[lng, lat]`. */
export const FALLBACK_CENTER = [138.25, 36.2]
export const FALLBACK_ZOOM = 5

export const MAX_ZOOM = 19

/** The drop every pin on the site is cut from, exported so a legend can draw one. */
export const PIN_PATH = 'M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7z'

export const PIN_COLOR = '#b3403f'
export const NEIGHBOR_COLOR = '#8b8798'

/*
  The last point taken before the file and the first after - the two that place
  it. Cool for behind, warm for ahead, both full size.
  See docs/features/maps.md.
*/
export const BEFORE_COLOR = '#4f7ca8'
export const AFTER_COLOR = '#3f8f6f'

function pinSvg(inner, size, color) {
  return (
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">` +
    `<path d="${PIN_PATH}" fill="${color}" stroke="#fff" stroke-width="1.2"/>${inner}</svg>`
  )
}

/** A DOM element the map can attach as a marker, sized to the icon. */
function iconElement(className, inner, size, color) {
  const element = document.createElement('div')
  element.className = className
  element.style.width = `${size}px`
  element.style.height = `${size}px`
  element.innerHTML = pinSvg(inner, size, color)
  return element
}

/** A single-media drop with a small white dot in the head. */
export function pinIconOf(color = PIN_COLOR, size = 30) {
  return iconElement('trip-pin', '<circle cx="12" cy="9" r="3" fill="#fff"/>', size, color)
}

/** The same drop, larger, with the child count inside the head. */
export function clusterIconOf(count, color = PIN_COLOR) {
  const size = 42
  const fontSize = count >= 1000 ? 6 : count >= 100 ? 7 : 8
  const inner =
    `<text x="12" y="9" text-anchor="middle" dominant-baseline="central" fill="#fff" ` +
    `font-family="inherit" font-weight="700" font-size="${fontSize}">${count}</text>`
  return iconElement('trip-pin', inner, size, color)
}

/* The square photo pin the trip and day maps draw. Smaller than the teardrop,
   with a white frame instead of a filled drop, and the same miniature-then-
   preview pair every wall of thumbnails uses. See docs/features/maps.md. */
export const PHOTO_PIN_SIZE = 44
export const PHOTO_PIN_TAIL = 7
/** The preview's own fade, which the miniature has to outlive before it goes. */
const PIN_PREVIEW_FADE_MS = 300

/** How long a pile shows one member before the shared ticker turns it. */
export const PILE_CYCLE_MS = 5000
/** The pile's own turn; the same beat as `MediaStrip` and the viewer. */
export const PILE_SLIDE_MS = 600
/** The curve `MediaStrip` uses, so a pile turn and a page turn read alike. */
export const PILE_EASING = 'cubic-bezier(0.2, 0.9, 0.3, 1)'

/**
 * The pile's turn, off by default.
 *
 * | `PILE_TURN` | Pile shows | Ticker |
 * | --- | --- | --- |
 * | `false` | one member's full pair, miniature **and** preview, as a lone pin | none |
 * | `true` | miniatures only, sliding every `PILE_CYCLE_MS` on one shared tick | one timer per map |
 *
 * The turn is visually busy, and loading a preview per pile is bounded by the
 * marker budget; the quiet mode is what ships. See docs/features/maps.md.
 */
export const PILE_TURN = false

/** One `<img>` of a two-stage picture, with the crop the shared class carries. */
function stageImage(className, src) {
  const image = document.createElement('img')
  image.className = className
  image.alt = ''
  image.setAttribute('aria-hidden', 'true')
  image.draggable = false
  image.src = src
  return image
}

/**
 * Puts one file's two-stage picture into a stage: the blurred miniature under
 * the preview, which fades in over it once it is whole and then lets the base
 * go. **One markup for the pin, the pile and the album**, and the CSS classes
 * are the grid tile's own, so the crop and the blur cannot drift.
 * See docs/features/maps.md.
 */
function setStagePicture(stage, media) {
  stage.classList.remove('is-ready')
  stage.querySelectorAll('img').forEach((node) => node.remove())

  const miniature = miniatureSrc(media)
  const preview = previewSrc(media)
  const nodes = []
  let base = null
  let shot = null
  if (miniature) {
    base = stageImage('thumb-base', miniature)
    nodes.push(base)
  }
  if (preview) {
    shot = stageImage('thumb-shot', preview)
    nodes.push(shot)
  }

  nodes.forEach((node) => stage.append(node))

  if (!shot) return
  shot.addEventListener(
    'load',
    () => {
      stage.classList.add('is-ready')
      // The base is covered pixel for pixel from here on, and a live blur on
      // every mark is the one cost this map cannot pay. As in the viewer.
      if (base) window.setTimeout(() => base.remove(), PIN_PREVIEW_FADE_MS)
    },
    { once: true },
  )
}

/** Writes a chip's hour, hiding the chip when the file has none to show. */
function writeClock(clock, media, locale) {
  const text = formatShortTime(media?.created, locale)
  clock.textContent = text
  clock.hidden = !text
}

/** The chip a day mark stamps above its frame: the hour of the file it shows. */
function clockChip(media, locale) {
  const clock = document.createElement('span')
  clock.className = 'trip-photo-time'
  writeClock(clock, media, locale)
  return clock
}

/** Rewrites a standing chip for a face change, never making one where none is. */
function setClockChip(root, media, locale) {
  const clock = root?.querySelector?.('.trip-photo-time')
  if (clock) writeClock(clock, media, locale)
}

/**
 * One square photo pin as a DOM element, the map attaching it as a marker.
 * `withTime` stamps the file's own clock above the frame - a **day** map is read
 * as a sequence of hours, so there the hour is worth saying, and `locale` shapes
 * that clock. The trip map takes neither. See docs/features/maps.md.
 */
export function photoPinIcon(media, { withTime = false, locale = '' } = {}) {
  const root = document.createElement('div')
  root.className = 'trip-photo-pin'

  const box = document.createElement('div')
  box.className = 'trip-photo-pin-box thumb-stage'
  setStagePicture(box, media)
  root.append(box)

  // The clock stands **above** the frame, outside the picture's box, so a long
  // stamp is not cut to a 40px picture. A pile and the trip map carry nothing.
  if (withTime) root.append(clockChip(media, locale))

  return root
}

/**
 * A pile of pins: **the pin's own shape**, a 44x51 frame with the same tail and
 * its ground at the bottom centre, so a pile opens into a preview by the same
 * movement a single pin does. The count sits as a badge in the corner; what the
 * picture shows follows `PILE_TURN`. See docs/features/maps.md.
 */
export function photoClusterIcon(items, { withTime = false, locale = '' } = {}) {
  const list = Array.isArray(items) ? items : []
  const root = document.createElement('div')
  root.className = 'trip-photo-cluster'

  const box = document.createElement('div')
  box.className = 'trip-photo-cluster-box thumb-stage'

  if (!PILE_TURN) {
    // The member's own two-stage picture, exactly as a lone pin draws it.
    setStagePicture(box, list[0])
    root.__pile = { cursor: 0, locale }
  } else {
    const current = document.createElement('img')
    current.className = 'trip-photo-cluster-img'
    current.alt = ''
    current.setAttribute('aria-hidden', 'true')
    const source = clusterMemberSrc(list[0])
    if (source) current.src = source

    // The layer that slides in. It waits off to the right until a turn.
    const incoming = document.createElement('img')
    incoming.className = 'trip-photo-cluster-img'
    incoming.alt = ''
    incoming.setAttribute('aria-hidden', 'true')
    incoming.style.transform = 'translateX(100%)'

    box.append(current, incoming)
    root.__pile = { cursor: 0, current, incoming, locale }
  }

  root.append(box)

  const badge = document.createElement('span')
  badge.className = 'trip-photo-cluster-count'
  badge.textContent = String(list.length)
  root.append(badge)

  // The chip a day pin wears, for the member the pile's face is on: a day is read
  // as a sequence of hours, and a pile is a place in it. See docs/features/maps.md.
  if (withTime) root.append(clockChip(list[0], locale))

  return root
}

/** The picture a turned pile member shows: **its miniature only**. */
export function clusterMemberSrc(media) {
  return miniatureSrc(media)
}

/**
 * Turns a pile to its next member. The incoming layer slides in from the right
 * while the one on show leaves to the left, then the two swap roles, so the pile
 * never blanks between members. `items` is the marker's current group, and the
 * member now on show is returned so the marker can publish it.
 */
export function advancePile(root, items) {
  const pile = root?.__pile
  const list = Array.isArray(items) ? items : []
  if (!pile || !PILE_TURN || list.length < 2) return pile?.cursor ?? 0

  pile.cursor = (pile.cursor + 1) % list.length
  const source = clusterMemberSrc(list[pile.cursor])
  if (!source) return pile.cursor

  // The chip follows the face, or it would name the member that just left.
  setClockChip(root, list[pile.cursor], pile.locale)

  const { current, incoming } = pile
  incoming.src = source

  incoming.style.transition = 'none'
  incoming.style.transform = 'translateX(100%)'
  // Laid out before the slide is armed, or the first frame starts from nowhere.
  void incoming.offsetWidth

  const slide = `transform ${PILE_SLIDE_MS}ms ${PILE_EASING}`
  current.style.transition = slide
  incoming.style.transition = slide
  current.style.transform = 'translateX(-100%)'
  incoming.style.transform = 'translateX(0)'

  window.setTimeout(() => {
    current.style.transition = 'none'
    incoming.style.transition = 'none'
    current.src = source
    current.style.transform = 'translateX(0)'
    incoming.style.transform = 'translateX(100%)'
  }, PILE_SLIDE_MS + 20)

  return pile.cursor
}

/**
 * Puts a pile's face on a named member with no slide, so a close lands on the
 * file that flew in and the ticker starts its beat from there. `cursor` is the
 * member's position in the pile's own group. See docs/features/maps.md.
 */
export function setPileFace(root, items, cursor) {
  const pile = root?.__pile
  const list = Array.isArray(items) ? items : []
  if (!pile || !list.length || cursor == null) return

  const index = ((cursor % list.length) + list.length) % list.length
  pile.cursor = index
  setClockChip(root, list[index], pile.locale)

  if (PILE_TURN) {
    const source = clusterMemberSrc(list[index])
    if (!source) return
    pile.current.style.transition = 'none'
    pile.current.src = source
    pile.current.style.transform = 'translateX(0)'
    return
  }

  const box = root.querySelector?.('.trip-photo-cluster-box')
  if (box) setStagePicture(box, list[index])
}

/** A control whose element is built once and is never collapsed behind a toggle. */
function elementControl(className, html) {
  let element = null
  return {
    onAdd() {
      element = document.createElement('div')
      element.className = className
      element.innerHTML = html
      return element
    },
    onRemove() {
      element?.remove()
      element = null
    },
  }
}

/*
  The Maptoolkit logo and the copyright line the Community License wants on every
  map, at every size, never behind a toggle. MapLibre's own attribution control
  collapses, so both are controls of our own with `attributionControl: false`.
  See docs/features/maps.md.
*/
function applyChrome(map, spec) {
  const attribution = elementControl('trip-map-attribution', spec.attribution)
  map.addControl(attribution, 'bottom-right')
  if (!spec.logo) return
  const logo = elementControl(
    'trip-map-logo',
    `<a href="https://www.maptoolkit.org/" target="_blank" rel="noopener">` +
      `<img src="${spec.logo}" alt="Maptoolkit"></a>`,
  )
  map.addControl(logo, 'bottom-left')
}

/*
  A bare wheel scrolls the page and never touches the map. Ctrl/Cmd + wheel is
  left to MapLibre's own scroll zoom, so the modifier gets its smooth,
  trackpad-aware zoom and the page zoom is stopped by MapLibre itself. The guard
  sits in the capture phase, before the map's own listener. See maps.md.
*/
function addWheelGuard(container, onScrollHint) {
  container.addEventListener(
    'wheel',
    (event) => {
      if (event.ctrlKey || event.metaKey) return
      onScrollHint?.()
      event.stopPropagation()
    },
    { passive: true, capture: true },
  )
}

/*
  MapLibre reserves Ctrl+drag for rotation and ignores a drag that carries the
  modifier, so a pan with Ctrl held does nothing. Rotation is off on every map
  here, so the same press is re-dispatched without the modifier. The moves that
  follow are accepted as they are - only the start is checked. See maps.md.
*/
function addCtrlDragPan(map, container) {
  container.addEventListener(
    'mousedown',
    (event) => {
      if (!event.ctrlKey || event.button !== 0) return
      event.stopPropagation()
      map.getCanvasContainer().dispatchEvent(
        new MouseEvent('mousedown', {
          bubbles: true,
          cancelable: true,
          view: window,
          button: 0,
          buttons: 1,
          clientX: event.clientX,
          clientY: event.clientY,
        }),
      )
    },
    true,
  )
}

/** The viewport area above which the pixel ratio is capped hardest. */
const LARGE_VIEWPORT_AREA = 1920 * 1080
/** Hosts already warmed this page, so a second map opens no second connection. */
const WARMED_HOSTS = new Set()

/** One `preconnect`, made once per host. */
function warmHost(host) {
  if (WARMED_HOSTS.has(host)) return
  WARMED_HOSTS.add(host)
  const link = document.createElement('link')
  link.rel = 'preconnect'
  link.href = `https://${host}`
  link.crossOrigin = ''
  document.head.append(link)
}

/**
 * Opens a connection to the provider's tile, glyph and sprite hosts before the
 * first tile is asked for, so the first paint pays no extra TLS handshake.
 */
function warmHosts(provider) {
  for (const host of provider?.hosts ?? []) warmHost(host)
}

/**
 * The canvas' pixel ratio, capped on a large viewport: painting cost scales with
 * the framebuffer, and a 4K map at an OS scale above 1.0 would otherwise
 * allocate a canvas several times the screen. See plans/maps-performance.md.
 */
function pixelRatioFor(container) {
  const area = (container.clientWidth || 0) * (container.clientHeight || 0)
  const base = window.devicePixelRatio || 1
  return Math.min(base, area > LARGE_VIEWPORT_AREA ? 1.25 : 1.5)
}

/**
 * A base map on the environment's provider, in the theme's scheme. By default
 * the wheel scrolls the page and only Ctrl/Cmd + wheel zooms, firing
 * `onScrollHint`; `wheelZoom` lifts that for a window-filling map. Rotation and
 * pitch are off: a photo backdrop stays flat. See docs/features/maps.md.
 */
export function createBaseMap(
  container,
  { center, zoom, onScrollHint, wheelZoom = false, scheme = 'light' } = {},
) {
  const spec = mapStyleFor(scheme)
  warmHosts(PROVIDERS[MAP_PROVIDER])
  const map = new Map({
    container,
    style: spec.style,
    center: center ?? FALLBACK_CENTER,
    zoom: zoom ?? FALLBACK_ZOOM,
    maxZoom: MAX_ZOOM,
    attributionControl: false,
    // Painting cost scales with the framebuffer, so a large viewport is capped.
    pixelRatio: pixelRatioFor(container),
    // A vector style cross-fades its tiles; a shorter fade is a cheaper one.
    fadeDuration: 150,
    // Fewer refetches when a pan returns over ground already seen.
    maxTileCacheSize: isSmallDevice() ? 60 : 120,
    // Keeps the next zoom's tiles warm while the map is idle.
    prefetchZoomDelta: 4,
    // Label placement is the map's own main-thread cost, and one basemap source
    // is enough for the labels to collide within. See docs/features/maps.md.
    crossSourceCollisions: false,
    renderWorldCopies: false,
    dragRotate: false,
    pitchWithRotate: false,
    touchPitch: false,
    maxPitch: 0,
    // MapLibre's scroll zoom is always on: it is the whole guarded path's zoom,
    // and the guard holds a bare wheel back from the map. See maps.md.
    scrollZoom: true,
  })
  map.__scheme = scheme
  applyChrome(map, spec)
  addCtrlDragPan(map, container)
  if (!wheelZoom) addWheelGuard(container, onScrollHint)
  return map
}

/** Swaps the basemap when the theme's light/dark scheme changes. */
export function setBaseScheme(map, scheme) {
  if (!map || map.__scheme === scheme) return
  map.__scheme = scheme
  map.setStyle(mapStyleFor(scheme).style)
}
